### ISSUE TITLE
How to obtain loading progress in real time

### ISSUE THREAD

**Issue by jiawenquan** [haestflod/generic-3Dproduct-viewer#4]
I tried to get the model loading progress in` loading-spinner`, but failed

**Comment by haestflod** [comment]
Currently the progress is impossible to get unless you're after like 0 / 2 models loaded. 
But the current setup also just uses an integer that increments all the time. So if you load 1 model it'd be `0 / 1`,

If you load a second model 30 seconds later it would show at `1 / 2`.

But a % is not possible at the mment.

It would have to get the total bytes of the XHR request and probably pass it along to the 
`ProductConfigurationEvent.Loading_Started` event 

And then add a second event 
`ProductConfigurationEvent.Loading_Progress`  where it updates the bytes downloaded 

And that would be used for a %. 

I'm not sure how to access the XHR request in the Three.js loader, as far as I know they do have an onupdate event so might be possible there to get the bytes.

**Comment by haestflod** [comment]
It can't get the % progress on images that's using three.js ImageLoader. Because there's no XHR to hook up to.

So if you load a GLTF model it'll be stuck at 100% while the textures load.
After investigating I believe one would have to override the ImageLoader class to use XHR and create the image from a blob instead of from src.
https://stackoverflow.com/questions/14218607/javascript-loading-progress-of-an-image

**Comment by haestflod** [comment]
Closed y PR #7
